"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const router = (0, express_1.default)();
const client_controllers_1 = require("../controllers/client.controllers");
const authorization = require("../middleware/authorization");
router.get("/user:id/clientes", client_controllers_1.getClients);
router.get("/cliente/:id", client_controllers_1.getClient);
router.post("/nuevo-cliente", client_controllers_1.addClient);
router.delete("/user:userId/cliente:clientId", client_controllers_1.deleteClient);
router.patch("/cliente/:id", client_controllers_1.updateClient);
router.put("/user:userId/cliente:clientId/agregar-saldo", client_controllers_1.addToClientBalance);
router.put("/user:userId/cliente:clientId/descontar-saldo", client_controllers_1.substractFromClientBalance);
router.get("/user:id/buscar-cliente", client_controllers_1.searchClient);
router.get("/user:id/clientes/ordenar-por-nombre-asc", client_controllers_1.orderByClientNameAsc);
router.get("/user:id/clientes/ordenar-por-nombre-desc", client_controllers_1.orderByClientNameDesc);
router.get("/user:id/clientes/ordenar-por-saldo-asc", client_controllers_1.orderByClientBalanceAsc);
router.get("/user:id/clientes/ordenar-por-saldo-desc", client_controllers_1.orderByClientBalanceDesc);
router.get("/user:userId/clientes/cantidad-clientes", client_controllers_1.getClientsQuantity);
exports.default = router;
