"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const operation_controller_1 = require("../controllers/operation.controller");
const router = (0, express_1.Router)();
exports.router = router;
router.get("/user:id/operation", operation_controller_1.getTodayOperationData);
router.get("/user:id/total-operation", operation_controller_1.getFullOperationData);
router.post("/user:id/month-operation", operation_controller_1.getMonthOperationData);
router.get("/user:id/clientes/saldo-total", operation_controller_1.getFullClientBalance);
